config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :restaurants
  resources :dishes, except: [:index]
  resources :tabs, only: [:new, :index, :show] do
    resources :dishes, only: [:index]
    resources :tab_dishes, only: [:create, :destroy]
    resources :split, only: [:show]
  end

  get 'tabs/:id/split', to: 'split#show'

  resources :bills, only: [:create, :show, :index] do
    resources :payments, only: :new
    resources :tab_dishes, only: [:index]
  end
  post "/bills_split", to: "bills#create_split"

  resources :bills_tab_dishes, only: [:index]

  resources :tab_dishes do
    member do
      post 'add_unit'
      # delete 'remove_unit'
      # post 'remove_unit'
    end
  end

  # get 'test/:tab_dish_id', to: 'tab_dishes#destroy', as: :test
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/split_controller.rb
class SplitController < ApplicationController
  def show
    @tab = Tab.find(params[:id])
    @dish = Dish.find(params[:id])
  end
end

app/views/split/show.html.erb
<div class="container">
  <h1 class="logo">My Tab</h1>
  <div class="row justify-content-sm-between">
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <h2>Search & add from full Bill </h2>
       <form class="form-inline md-form mr-auto mb-4">
       <i class="fas fa-search" aria-hidden="true"></i>
          <%= form_tag tab_dishes_path, method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control mr-sm-2",
              placeholder: "Find an item" %>
              <%= submit_tag "Search", class: "btn btn-outline-primary" %>
          <% end %>
      </div>
    </div>
  </div>
</div>


<% @tab.dishes.each do |dish| %>
  <div class="container justify-content-center">
    <div class="card my-2">
      <div class="card-body">
        <h5 class="card-title">
          <%= dish.name %>
          <span class="badge bg-secondary">
            <%= TabDish.where(tab: @tab, dish: dish).first.quantity %>
          </span>
        </h5>

        <h6 class="card-subtitle mb-2 text-muted"><%= display_price(dish.price_cents) %></h6>
        <%= link_to "-", add_unit_tab_dish_path(tab_id: @tab.id, dish_id: dish.id, dish_action: 'remove'), class: "btn", method: :post if user_signed_in? %>
        <%= link_to "+", add_unit_tab_dish_path(tab_id: @tab.id, dish_id: dish.id, dish_action: 'add'), class: "btn", method: :post if user_signed_in? %>
      </div>
    </div>
  </div>
<% end %>




<div class="container mt-4">
  <div class="d-flex justify-content-around">
   <%= link_to 'Add items', tab_dishes_path(@tab), class: 'btn-rounded btn btn-dark btn-small' if current_user %>
    <%= form_tag bills_path do %>
      <%= hidden_field_tag 'tab_id', @tab.id %>
      <%= submit_tag 'Pay', class: 'btn btn-dark btn small btn-rounded' %>
    <% end %>
  </div>
</div>