config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :restaurants
  resources :dishes, except: [:index]
  resources :tabs, only: [:new, :index, :show] do
    resources :dishes, only: [:index]
    resources :tab_dishes, only: [:create, :destroy]
    resources :split, only: [:show]
  end

  get 'tabs/:id/split', to: 'split#show'

  resources :bills, only: [:create, :show, :index] do
    resources :payments, only: :new
    resources :tab_dishes, only: [:index]
  end
  post "/bills_split", to: "bills#create_split"

  resources :bills_tab_dishes, only: [:index]

  resources :tab_dishes do
    member do
      post 'add_unit'
      # delete 'remove_unit'
      # post 'remove_unit'
    end
  end

  # get 'test/:tab_dish_id', to: 'tab_dishes#destroy', as: :test
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tab.rb
class Tab < ApplicationRecord
  belongs_to :restaurant
  has_many :tab_dishes
  has_many :dishes, through: :tab_dishes

  enum status: [:open, :closed]
end

app/controllers/tabs_controller.rb
class TabsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @tabs = Tab.all
  end

  def show
    @tab = Tab.find(params[:id])
    @qr_code = RQRCode::QRCode.new("https://www.payjam.co/tabs/#{@tab.id}")
    @svg = @qr_code.as_svg(
    module_size: 25
  )
    @bill = Bill.new
  end

  def destroy
    redirect_to tab_dishes_path
  end

  def new
    @qr_code = RQRCode::QRCode.new("https://www.payjam.co/tabs/3")
    @svg = @qr_code.as_svg
  end

private

  def tab_params
    params.require(:tab).permit(:qr_code)
  end
end

app/views/tabs/index.html.erb
<div class="container">
  <h1 class="tables text-start mb-4 fw-bold">Tables</h1>

    <!-- Open tabs -->
    <h3 class="text-muted mb-3 fs-3">Active</h3>
    <% @tabs.open.each do |tab| %>
      <div class="card card-rounded p-3 mb-3 light-blue" style="background: #C8EEFF;">
        <div class="d-flex justify-content-between align-items-center">
          <h5 class="ms-3 mb-0">Table <%= tab.table_number %></h5>
          <%= link_to "View", tab_path(tab), class: "me-3" %>
        </div>
        <div class="d-flex justify-content-between mt-2">
          <p class="text-muted mb-0 ms-3"><%= tab.tab_dishes.count %> items</p>
          <p class="text-muted mb-0 me-3"><%= display_price(tab.total_cents) %></p>
        </div>
      </div>
    <% end %>

    <!-- Empty tabs -->
    <h3 class="text-muted mb-3 mt-5 fs-3">Empty</h3>
    <% @tabs.closed.each do |tab| %>
      <div class="card card-rounded p-3 mb-3">
        <div class="d-flex justify-content-between align-items-center">
          <h5 class="ms-3 mb-0">Table <%= tab.table_number %></h5>
          <%= link_to "Open", tab_path(tab), class: "py-2 badge rounded-pill bg-primary px-3 open-badge" %>
        </div>
      </div>
    <% end %>
  <%# </div> %>
</div>

app/views/tabs/new.html.erb
<div class="container my-5">
  <div class="row justify-content-center mx-2">
    <%= @svg.html_safe %>
  </div>
  <div class="row justify-content-center mx-2">
    <%= link_to 'Go to tab', tabs_path(7), class: 'btn-rounded btn btn-dark btn-small' %>
  </div>
</div>

app/views/tabs/show.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center mb-5">
    <h1 class="tables text-start mb-0 fw-bold">Table <%= @tab.table_number  %></h1>
    <h5 class="text-muted mb-0">Total: <%= display_price(@tab.total_cents) %></h5>
  </div>

  <% @tab.dishes.each do |dish| %>
    <div class="card card-rounded p-3 mb-3">
      <div class="d-flex align-items-start">
        <span class="badge bg-secondary py-2 align-content-start">
          <%= TabDish.where(tab: @tab, dish: dish).first.quantity %>
        </span>
        <div class="d-flex align-items-center ms-3 flex-grow-1">
          <div class="flex-grow-1">
            <h5 class="card-title mb-0"><%= dish.name %></h5>
            <h6 class="card-subtitle mb-0 text-muted">
              &thinsp;<%= display_price(dish.price_cents) %>
            </h6>
          </div>
          <div class="flex-shrink-0">
            <%= link_to content_tag(:i, "", class: ["fas", "fa-minus"]),
              add_unit_tab_dish_path( tab_id: @tab.id, dish_id: dish.id, dish_action: 'remove'),
                class: "text-primary fw-bold me-3",
                method: :post if user_signed_in? %>

            <%= link_to content_tag(:i, "", class: ["fas", "fa-plus"]),
              add_unit_tab_dish_path(tab_id: @tab.id, dish_id: dish.id, dish_action: 'add'),
                class: "text-primary fw-bold",
                method: :post if user_signed_in? %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="container mb-3">
  <% if user_signed_in? %>
    <div class="row justify-content-center mx-2 mt-2">
      <%= link_to 'Add items', tab_dishes_path(@tab), class: 'btn btn-primary btn-lg card-rounded' %>
    </div>
  <% end %>

  <!-- Payment buttons -->

    <!-- Pay all -->
    <%= form_tag bills_path do %>
      <%= hidden_field_tag 'tab_id', @tab.id %>
      <div class="row justify-content-center mx-2 mt-2">
        <%= submit_tag 'Pay all', class: 'btn btn-primary btn-lg card-rounded' %>
      </div>
    <% end %>

    <!-- Split bill (triggers the modal) -->
    <div class="row justify-content-center mx-2 mt-2">
      <button type="button" class="btn btn-primary btn-lg card-rounded" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Split the bill
      </button>
    </div>

</div>

<!-- Modal -->
<div class="modal fade rounded" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">How do you want to split?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@bill, url: bills_split_path) do |f| %>
          <%= hidden_field_tag :amount, @tab.total_cents %>
          <%= hidden_field_tag :tab_id, params[:id]  %>
            <div class="row justify-content-center mx-3 mt-3">
              <%= text_field_tag :number, nil, placeholder: 'Number of guests', class: "flex-grow-1 me-2 form-control card-rounded" %>
            </div>
            <div class="row justify-content-center mx-3 mt-3">
              <%= f.submit "Split evenly", class: 'btn btn-primary card-rounded px-4' %>
          </div>
        <% end %>
        <div>
          <h2 class="line-split my-5"><span class="fs-6 text-muted">OR</span></h2>
          <div class="row justify-content-center mx-3 mt-5">
            <a href="#" class="btn btn-primary card-rounded px-4">Custom split</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>