config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :restaurants
  resources :dishes, except: [:index]
  resources :tabs, only: [:new, :index, :show] do
    resources :dishes, only: [:index]
    resources :tab_dishes, only: [:create, :destroy]
    resources :split, only: [:show]
  end

  get 'tabs/:id/split', to: 'split#show'

  resources :bills, only: [:create, :show, :index] do
    resources :payments, only: :new
    resources :tab_dishes, only: [:index]
  end
  post "/bills_split", to: "bills#create_split"

  resources :bills_tab_dishes, only: [:index]

  resources :tab_dishes do
    member do
      post 'add_unit'
      # delete 'remove_unit'
      # post 'remove_unit'
    end
  end

  # get 'test/:tab_dish_id', to: 'tab_dishes#destroy', as: :test
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant
  belongs_to :category

  has_many :tab_dishes, dependent: :destroy
  has_many :tabs, through: :tab_dishes
  has_one_attached :photo
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @dish = Dish.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @dish = Dish.new(dish_params)
    @dish.restaurant = @restaurant
    if @dish.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def index
    # @categories = Category.all
    @tab = Tab.find(params[:tab_id])

    if params[:query].present?
      sql_query = "dishes.name ILIKE :query OR description ILIKE :query or categories.name ILIKE :query"
      @dishes = Dish.where(sql_query, query: "%#{params[:query]}%").joins(:category)
    else
      @dishes = Dish.all
    end
  end

  def show
    @dish = Dish.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy
    redirect_to restaurant_path(@dish.restaurant)
  end

  private

  def dish_params
    params.require(:dish).permit(:name, :price, :description, :category, :photo)
  end
end

app/views/dishes/destroy.html.erb
<h1>Dishes#destroy</h1>
<p>Find me in app/views/dishes/destroy.html.erb</p>

app/views/dishes/edit.html.erb
<h1>Dishes#edit</h1>
<p>Find me in app/views/dishes/edit.html.erb</p>

app/views/dishes/index.html.erb
<div class="container">
  <h1 class="tables text-start mb-4 fw-bold">Table <%= @tab.table_number  %></h1>
  <h3 class="text-muted mb-3 fs-3">Add items</h3>

  <div class="d-flex justify-content-between align-items-center my-4">
      <div>
        <%= form_tag tab_dishes_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
              class: "form-control card-rounded transparent",
              placeholder: "Find an item" %>
      </div>
      <div>
        <%= submit_tag "Search", class: "btn btn-primary card-rounded px-4" %>
      </div>
    <% end %>
  </div>
</div>

<div class="container accordion" id="categoryAccordion">
  <% @dishes.group_by(&:category).each do |category, dishes| %>
    <div class="accordion-item mb-2">
      <h2 class="accordion-header" id="categoryItemHeading-<%= category.id %>">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" style="background-color: white;" data-bs-target="#categoryItem-<%= category.id %>">
          <%= category.name %>
        </button>
      </h2>

      <div id="categoryItem-<%= category.id %>" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingOne">
        <div class="accordion-body">
          <% dishes.each do |dish| %>
            <div class="container card my-3 justify-content-center">
              <div class="d-flex justify-content-between align-items-center py-2">
                <div>
                  <h5 class="card-title"><%= dish.name %></h5>
                  <h6 class="card-subtitle text-muted"><%= display_price(dish.price_cents) %></h6>
                </div>
                  <%= simple_form_for(@tab, method: :post, url: tab_tab_dishes_path) do |f| %>
                    <%= f.input :dish_id, input_html: { value: dish.id }, wrapper_html: { class: "d-none"}, as: :hidden %>
                    <%= f.submit "+", class: 'btn plus' %>
                  <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="container mb-3">
  <div class="row justify-content-center mx-2 mt-5">
    <%= link_to "Go to Tab", tab_path(@tab), class: "btn btn-primary btn-lg card-rounded" %>
  </div>
</div>

app/views/dishes/show.html.erb
<h1>Dishes#show</h1>
<p>Find me in app/views/dishes/show.html.erb</p>

app/views/dishes/update.html.erb
<h1>Dishes#update</h1>
<p>Find me in app/views/dishes/update.html.erb</p>